tearEffects = ds_list_create()
ds_list_add(tearEffects,'slowing')
ds_list_add(tearEffects,'freezing')
ds_list_add(tearEffects,'piercing')
ds_list_add(tearEffects,'spectral')
ds_list_add(tearEffects,'burning')
ds_list_add(tearEffects,'homing')
tearColors = ds_list_create()
ds_list_add(tearColors,"55,55,55")
